# Generated by Django 2.2.6 on 2019-11-11 17:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sections_count', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Разделов')),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Последнее обновление')),
                ('seo_title', models.CharField(blank=True, max_length=250, verbose_name='Заголовок (SEO)')),
                ('seo_keywords', models.CharField(blank=True, max_length=150, verbose_name='Ключевые слова (SEO)')),
                ('seo_description', models.CharField(blank=True, max_length=250, verbose_name='Описание (SEO)')),
                ('sort_key', models.IntegerField(db_index=True, default=0, verbose_name='Ключ сортировки')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('threads_count', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Тем')),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Последнее обновление')),
                ('seo_title', models.CharField(blank=True, max_length=250, verbose_name='Заголовок (SEO)')),
                ('seo_keywords', models.CharField(blank=True, max_length=150, verbose_name='Ключевые слова (SEO)')),
                ('seo_description', models.CharField(blank=True, max_length=250, verbose_name='Описание (SEO)')),
                ('sort_key', models.IntegerField(db_index=True, default=0, verbose_name='Ключ сортировки')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='forum.Category', verbose_name='Категория')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Раздел категории',
                'verbose_name_plural': 'Разделы категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_allowed', models.BooleanField(db_index=True, default=True, verbose_name='Комментирование разрешено')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('article_system_id', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='id статьи из статейной системы')),
                ('text', models.TextField(verbose_name='Текст темы')),
                ('posts_count', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Ответов')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('last_updated', models.DateTimeField(db_index=True, verbose_name='Дата обновления')),
                ('image1', models.ImageField(blank=True, upload_to='thread_images', verbose_name='Изображение 1')),
                ('image2', models.ImageField(blank=True, upload_to='thread_images', verbose_name='Изображение 2')),
                ('image3', models.ImageField(blank=True, upload_to='thread_images', verbose_name='Изображение 3')),
                ('seo_title', models.CharField(blank=True, max_length=250, verbose_name='Заголовок (SEO)')),
                ('seo_keywords', models.CharField(blank=True, max_length=150, verbose_name='Ключевые слова (SEO)')),
                ('seo_description', models.CharField(blank=True, max_length=250, verbose_name='Описание (SEO)')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='forum.Section', verbose_name='Секция')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Текст сообщения')),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True, verbose_name='Айпишник')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата отправки')),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Дата обновления')),
                ('image1', models.ImageField(blank=True, upload_to='posts_images', verbose_name='Изображение 1')),
                ('image2', models.ImageField(blank=True, upload_to='posts_images', verbose_name='Изображение 2')),
                ('image3', models.ImageField(blank=True, upload_to='posts_images', verbose_name='Изображение 3')),
                ('thread', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.Thread', verbose_name='Тема')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['date_created'],
            },
        ),
    ]
