# Generated by Django 2.2.6 on 2019-11-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191106_1122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
