# Generated by Django 2.2.6 on 2019-11-06 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Аватар')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='Город')),
                ('gender', models.CharField(choices=[('male', 'мужской'), ('female', 'женский')], default='male', max_length=6, verbose_name='Пол')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='День рождения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
