# Generated by Django 2.2.6 on 2019-10-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_sort',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата сортировки'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='main_photos', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=300, verbose_name='Ключевики (SEO)'),
        ),
    ]
