# Generated by Django 2.2.6 on 2019-10-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20191021_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип статьи',
                'verbose_name_plural': 'Типы статей',
                'db_table': 'articles_articletype',
            },
        ),
        migrations.AlterModelOptions(
            name='informationtype',
            options={'verbose_name': 'Тип информации', 'verbose_name_plural': 'Типы информации'},
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=300, verbose_name='Ключ.слова (SEO)'),
        ),
    ]
