# Generated by Django 2.2.6 on 2019-10-21 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20191021_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.ArticleType', verbose_name='Тип статьи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='info_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.InformationType', verbose_name='Тип информации'),
        ),
    ]
