# Generated by Django 2.2.6 on 2019-10-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20191021_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='twitter_export',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Экспорт в Твиттер'),
        ),
        migrations.AddField(
            model_name='article',
            name='twitter_exported',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
    ]
