# Generated by Django 2.2.6 on 2019-10-23 11:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20191022_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная')),
                ('publication_start', models.DateTimeField(default=datetime.datetime.now, verbose_name='Начало публикации')),
                ('publication_end', models.DateTimeField(blank=True, null=True, verbose_name='Конец публикации')),
                ('bold', models.BooleanField(default=False, verbose_name='Жирный шрифт')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Новость блока «Оперативное»',
                'verbose_name_plural': 'Новости блока «Оперативное»',
                'db_table': 'articles_operatively',
            },
        ),
    ]
