# Generated by Django 2.2.6 on 2019-10-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20191023_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationalarticle',
            name='order',
        ),
    ]
