# Generated by Django 2.2.6 on 2019-10-23 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_operationalarticle_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationalarticle',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='operationalarticle',
            name='publication_end',
        ),
        migrations.RemoveField(
            model_name='operationalarticle',
            name='publication_start',
        ),
        migrations.AlterField(
            model_name='operationalarticle',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Article'),
        ),
    ]
