# Generated by Django 2.2.6 on 2019-10-23 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20191023_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article'),
        ),
    ]
