# Generated by Django 2.2.6 on 2019-10-23 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20191023_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_to',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Конец публикации'),
        ),
        migrations.AlterField(
            model_name='operationalarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article', verbose_name='Статья'),
        ),
    ]
