# Generated by Django 2.2.6 on 2019-10-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20191028_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citydetails',
            name='big_block',
        ),
        migrations.AddField(
            model_name='article',
            name='big_block',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Выводить в «Большом блоке»'),
        ),
    ]
