# Generated by Django 2.2.6 on 2019-10-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20191028_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicleRubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='articletype',
            options={'verbose_name': 'Шаблон отображения', 'verbose_name_plural': 'Типы шаблонов'},
        ),
        migrations.AlterField(
            model_name='citydetails',
            name='placement_unit',
            field=models.CharField(choices=[('1', '1 экран'), ('2', '2 экран'), ('3', '3 экран')], default=1, max_length=1, verbose_name='Место'),
        ),
    ]
