# Generated by Django 2.2.6 on 2019-10-30 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_auto_20191030_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chroniclearticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='chroniclearticle',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.ChronicleRubric', verbose_name='Тема хроники'),
        ),
    ]
