# Generated by Django 2.2.6 on 2019-10-30 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_auto_20191030_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chroniclearticle',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.ChronicleRubric', verbose_name='Тема хроники'),
        ),
    ]
