# Generated by Django 2.2.6 on 2019-10-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_testdrivearticle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chroniclearticle',
            options={'verbose_name': '«Хроника»', 'verbose_name_plural': '«Хроника»'},
        ),
        migrations.AlterModelOptions(
            name='citydetails',
            options={'verbose_name': '«Городские новости»', 'verbose_name_plural': '«Городские новости»'},
        ),
        migrations.AlterModelOptions(
            name='operationalarticle',
            options={'verbose_name': '«Оперативное»', 'verbose_name_plural': '«Оперативное»'},
        ),
        migrations.AlterModelOptions(
            name='testdrivearticle',
            options={'verbose_name': '«Тест-драйв»', 'verbose_name_plural': '«Тест-драйвы»'},
        ),
    ]
