# Generated by Django 2.2.6 on 2019-11-05 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_auto_20191030_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='articles.Rubric', verbose_name='Рубрика')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='articles.Tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Популярный тег',
                'verbose_name_plural': 'Популярные теги',
                'ordering': ['tag__text'],
            },
        ),
    ]
