# Generated by Django 2.2.6 on 2019-11-07 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_auto_20191107_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chroniclearticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronicle_articles', to='articles.Article', verbose_name='Статья'),
        ),
    ]
