# Generated by Django 2.2.6 on 2019-10-16 14:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cmstemplates', '0002_templatefragment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefragment',
            name='text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Текст шаблона'),
        ),
    ]
