# Generated by Django 2.2.6 on 2019-10-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmstemplates', '0003_auto_20191016_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefragment',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Текст шаблона'),
        ),
    ]
