# Generated by Django 2.2.6 on 2019-10-21 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmstemplates', '0005_sitelogo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitelogo',
            options={'verbose_name': 'Логотип сайта', 'verbose_name_plural': 'Логотипы сайта'},
        ),
    ]
