# Generated by Django 2.2.6 on 2019-10-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmstemplates', '0007_newsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsettings',
            name='name',
            field=models.CharField(db_index=True, default=1, max_length=55, verbose_name='Название раздела'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsettings',
            name='commercial_main_news',
            field=models.PositiveSmallIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], verbose_name='Макс. количество статей'),
        ),
    ]
